apiVersion: v1
kind: Service
metadata:
  name: pixel-visualizer
  labels:
    app: pixel-visualizer
spec:
  clusterIP: None
  selector:
    app: pixel-visualizer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pixel-visualizer
  labels:
    app: pixel-visualizer
spec:
  selector:
    matchLabels:
      app: pixel-visualizer
  serviceName: pixel-visualizer
  replicas: 1
  template:
    metadata:
      labels:
        app: pixel-visualizer
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name" : "pixel-network"
          }
        ]'
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: BIND_ADDRESS
              value: {{ required "An sender IP must be provided" .Values.sender_ip | quote }}
            - name: CAPTURE_GAIN
              value: {{ .Values.capture_gain | default "5" | quote }}
          resources:
            limits:
              device.k8.ttar.org/audio: "1"
              device.k8.ttar.org/usbsound: "1"
          securityContext:
            capabilities:
              add: ["SYS_NICE"]
      terminationGracePeriodSeconds: 0