apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixel-visualizer
  labels:
    app: pixel-visualizer
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: pixel-visualizer
  template:
    metadata:
      labels:
        app: pixel-visualizer
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: BIND_ADDRESS
              value: {{ .Values.bind_address | default "0.0.0.0" | quote }}
          resources:
            limits:
              device.k8.ttar.org/audio: "1"
              device.k8.ttar.org/usbsound: "1"
          securityContext:
            capabilities:
              add: ["SYS_NICE"]
      terminationGracePeriodSeconds: 0