name: Publish to helm

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_USER: ttarhan
  IMAGE_NAME: ttarhan/pixel-audio-visualizer

jobs:
  helm-publish:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.IMAGE_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
      - name: Helm chart version
        run: |
          sed -i "s/VERSION/${{ steps.meta.outputs.tags }}/" chart/Chart.yaml
      - name: Helm chart package
        run: |
          helm package ./chart
      - name: Helm chart push
        run: |
          helm chart push ./pixel-audio-visualizer-${{ steps.meta.outputs.tags }}.tgz oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-chart